### ISSUE TITLE
[X not included in the provided text]

### ISSUE THREAD

**Issue by wolfassi123** [groundxai/groundx-sdks#63]
Hello, I have been testing your solutions for a few days now and I can say that I am extremely impressed. 

I was testing on one of the documents and I got the following

`[X not included in the provided text]` from the fetched chunks.

I noticed that in the chunk at some point the a certain list is ommited and replace by this message.

Can you please further elaborate what that is and why it showed up?

**Comment by blfletcher** [comment]
Hey there, would you be willing to contact us at support@eyelevel.ai? If you can share the document or your account email, that would help us trace the issue you're referring to.
